'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import { useStore } from './store/zustand'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const profileState = useStore(state => state.profileState)
  const authModalState = useStore(state => state. authModalState)
  const mapModalState =  useStore(state => state.mapModalState)
  return (
    <html lang="en">
      <body className={`${profileState && "overflow-hidden"} ${authModalState  && "overflow-hidden"} ${mapModalState && "overflow-hidden"}`}>{children}</body>
    </html>
  )
}
